[package]
name = "txs"
version = "0.1.0"
authors = ["Stjepan Golemac <stjepan.golemac@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1.5"
serde = { version = "1.0.120", features = ["derive"] }
structopt = "0.3.21"
rust_decimal = "1.10.1"
rust_decimal_macros = "1.10.1"
